### ISSUE TITLE
Build into Chrome extension

### ISSUE THREAD

**Issue by pschfr** [pschfr/retro-crt-startpage#2]

**Comment by pschfr** [comment]
Will reopen if I decide to work on this again....

**Comment by scar45** [comment]
I don't know how I missed the original 'issue' (task, really), but it sounds like a great idea! I will watch to see if you re-open it, as I think there are also some improvements that can be made as well, like creating a config page/modal to easily edit the links from JSON.

Life has been unkind to me regarding free time, but it's good to know that this little project sparked some interest. I still use it daily myself as a startpage, and I'm not sick of it yet...good sign I guess!
